### ISSUE TITLE
ESPN Monday Night Football

### ISSUE THREAD

**Issue by mophawka** [Tapiosinn/tv-logos#10]
**What logo would you like to see? Why?**
ESPN Monday Night Football

**What country is the channel shown?**
US

**Links(optional)**
https://static.www.nfl.com/image/private/t_photogallery/f_png/league/mpx0s6jwjrjbhfw9rfol.png
https://i.imgur.com/IR4M9rn.jpg

**Additional context(optional)**
Thank you for your consideration

**Comment by Tapiosinn** [comment]
@mophawka Is this the most current version of the logo? 
I think it looks like this now https://en.wikipedia.org/wiki/Monday_Night_Football
Can you confirm?

**Comment by mophawka** [comment]
> @mophawka Is this the most current version of the logo?
> I think it looks like this now https://en.wikipedia.org/wiki/Monday_Night_Football
> Can you confirm?

the first link is directly on nfls website. so i cant confirm or deny what wiki is suggesting but i would assume nfl has the correct logo?
if I may,  while I have your ear, I was planning on requesting Thursday night and Sunday night as well as separate threads. or would you recommend i just add them here? 

Thank you

**Comment by Tapiosinn** [comment]
@mophawka 
I found the wikipedia version on some 2021 promotional material so I'm going to use that one. And yeah I can also do the other ones.

**Comment by Tapiosinn** [comment]
@mophawka

https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-states/espn-monday-night-football-us.png
