### ISSUE TITLE
NFL Thursday Night Football

### ISSUE THREAD

**Issue by mophawka** [Tapiosinn/tv-logos#12]
**What logo would you like to see? Why?**
NFL Thursday Night Football

**What country is the channel shown?**
US

**Links(optional)**
https://static.www.nfl.com/image/private/f_auto/league/ilem8fkogrqrn3dxysqn

**Additional context(optional)**
Thank you again

**Comment by Tapiosinn** [comment]
@mophawka 
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-states/nfl-thursday-night-football-us.png
