### ISSUE TITLE
Sky Cinema New Channels

### ISSUE THREAD

**Issue by VoidMediaBoss** [Tapiosinn/tv-logos#13]
**What logo would you like to see? Why?**
Sky Cinema Back to School & Sky Cinema Assassins 

**What country is the channel shown?**
UK

**Links(optional)**
https://www.sky.com/tv-guide/20210910/4101-1

**Additional context(optional)**
N/A

**Comment by Tapiosinn** [comment]
@VoidMediaBoss 

**Sky Cinema Back to School**
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-kingdom/sky-cinema-back-to-school-uk.png

**Sky Cinema Back to School HD**
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-kingdom/hd/sky-cinema-back-to-school-hd-uk.png

**Sky Cinema Assassins**
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-kingdom/sky-cinema-assassins-uk.png

**Sky Cinema Assassins HD**
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-kingdom/hd/sky-cinema-assassins-hd-uk.png
