### ISSUE TITLE
UK Entertainment - MTV HD (New Logo)

### ISSUE THREAD

**Issue by VoidMediaBoss** [Tapiosinn/tv-logos#14]
**What logo would you like to see? Why?**
MTV HD (UK)

**What country is the channel shown?**
Sky UK

**Links(optional)**
Check SKY TV GUIDE online

**Additional context(optional)**
N/A

**Comment by Tapiosinn** [comment]
@VoidMediaBoss 
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-kingdom/hd/mtv-hd-uk.png
