### ISSUE TITLE
Eurosport 1, 2 HD and BBC One Oxford 

### ISSUE THREAD

**Issue by VoidMediaBoss** [Tapiosinn/tv-logos#16]
**What logo would you like to see? Why?**
Eurosport 1, 2 HD and BBC One Oxford 

**What country is the channel shown?**
UK

**Links(optional)**
https://www.sky.com/tv-guide/20211011/4101-1/

**Additional context(optional)**
Add any other context or screenshots about the logo request here.

**Comment by Tapiosinn** [comment]
Eurosport 1 & 2 HD added.

BBC One has updated all their logos to only say BBC ONE, regional logos removed.

@VoidMediaBoss
