### ISSUE TITLE
SparkSports NZ & Sky Sports Red Button

### ISSUE THREAD

**Issue by VoidMediaBoss** [Tapiosinn/tv-logos#17]
**What logo would you like to see? Why?**
SparkSports NZ & Sky Sports Red Button

**What country is the channel shown?**
SparkSports NZ & Sky Sports Red Button UK
 
**Links(optional)**
https://www.sparksport.co.nz/
https://sport-onthebox.com/wp-content/uploads/2020/09/Sky-Sports-Red-Button.png

**Additional context(optional)**
Add any other context or screenshots about the logo request here.

**Comment by Tapiosinn** [comment]
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-kingdom/sky-sports-red-button-uk.png
@VoidMediaBoss

**Comment by Tapiosinn** [comment]
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/new-zealand/spark-sport-nz.png
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/new-zealand/spark-sport-hz-nz.png
@VoidMediaBoss
