### ISSUE TITLE
Can you please add Sky Cinema with Icon pictures?

### ISSUE THREAD

**Issue by VoidMediaBoss** [Tapiosinn/tv-logos#19]
**What logo would you like to see? Why?**
Can you please add Sky Cinema with Icon pictures?

**What country is the channel shown?**
UK

**Links(optional)**
Links to the logo or website of channel.

**Additional context(optional)**
Add any other context or screenshots about the logo request here.

**Comment by Tapiosinn** [comment]
Added Sky Cinema Icon versions

https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-kingdom/sky-cinema-action-icon-uk.png
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-kingdom/sky-cinema-animation-icon-uk.png
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-kingdom/sky-cinema-comedy-icon-uk.png
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-kingdom/sky-cinema-drama-icon-uk.png
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-kingdom/sky-cinema-family-icon-uk.png
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-kingdom/sky-cinema-greats-icon-uk.png
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-kingdom/sky-cinema-hits-icon-uk.png
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-kingdom/sky-cinema-icon-uk.png
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-kingdom/sky-cinema-premiere-icon-uk.png
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-kingdom/sky-cinema-premiere-plus-icon-uk.png
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-kingdom/sky-cinema-sci-fi-horror-icon-uk.png
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-kingdom/sky-cinema-select-icon-uk.png
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-kingdom/sky-cinema-thriller-icon-uk.png

See frontpage for donation link. @VoidMediaBoss
