### ISSUE TITLE
Turkish Channels

### ISSUE THREAD

**Issue by UzunMuhalefet** [Tapiosinn/tv-logos#22]
**What logo would you like to see? Why?**
Kral TV, Kanal Avrupa, ATV Avrupa, Yol TV, TV8 Int, Powertürk

**What country is the channel shown?**
Turkey

**Links(optional)**
https://raw.githubusercontent.com/Jasmeet181/mediaportal-nordic-logos/master/TV/Kral%20TV.svg
https://raw.githubusercontent.com/Jasmeet181/mediaportal-de-logos/master/TV/Kanal%20Avrupa.png
https://raw.githubusercontent.com/Jasmeet181/mediaportal-de-logos/master/TV/ATV%20Avrupa.svg
https://raw.githubusercontent.com/Jasmeet181/mediaportal-de-logos/master/TV/Yol%20TV.png
https://raw.githubusercontent.com/Jasmeet181/mediaportal-de-logos/master/TV/TV8%20Int.png
https://raw.githubusercontent.com/Jasmeet181/mediaportal-de-logos/master/TV/PowerTurk%20TV.png

**Comment by Tapiosinn** [comment]
Logos added
@UzunMuhalefet
