### ISSUE TITLE
Kanal Sim Turkey

### ISSUE THREAD

**Issue by UzunMuhalefet** [Tapiosinn/tv-logos#23]
**What logo would you like to see? Why?**
Kanal Sim

**What country is the channel shown?**
Turkey

**Links(optional)**
https://www.facebook.com/kanal.sim

**Comment by Tapiosinn** [comment]
@UzunMuhalefet 

https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/turkey/kanal-sim-tr.png
