### ISSUE TITLE
TRT Spor and TRT 3 Spor

### ISSUE THREAD

**Issue by UzunMuhalefet** [Tapiosinn/tv-logos#24]
**What logo would you like to see? Why?**
TRT Spor and TRT 3 Spor

**What country is the channel shown?**
Turkey

**Links(optional)**
https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/TRT_Spor_logo_%282022%29.svg/1920px-TRT_Spor_logo_%282022%29.svg.png
https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/TRT_3_Spor_logo_%282022%29.svg/1920px-TRT_3_Spor_logo_%282022%29.svg.png

**Additional context(optional)**
TRT Spor and TRT 3 Spor changed their logos. I could not find a light-color version.

**Comment by UzunMuhalefet** [comment]
TRT Kürdi is in the same situation.

https://upload.wikimedia.org/wikipedia/commons/7/79/TRT_Kurd%C3%AE_logo.svg

**Comment by Tapiosinn** [comment]
Updated
https://github.com/Tapiosinn/tv-logos/blob/master/countries/turkey/trt-spor-tr.png

https://github.com/Tapiosinn/tv-logos/blob/master/countries/turkey/trt-3-spor-tr.png

https://github.com/Tapiosinn/tv-logos/blob/master/countries/turkey/trt-kurdi-tr.png

Might need to refresh cache if they don't update.
@UzunMuhalefet
