### ISSUE TITLE
NC Charlotte WCCB

### ISSUE THREAD

**Issue by mophawka** [Tapiosinn/tv-logos#25]
**What logo would you like to see? Why?**
Local Charlotte NC WCCB 

**What country is the channel shown?**
US

**Links(optional)**
[Links to the logo or website of channel.
https://wpcdn.us-east-1.vip.tn-cloud.net/www.wccbcharlotte.com/content/uploads/2015/09/Wccb_charlottes_cw.png

https://www.wccbcharlotte.com/

**Additional context(optional)**
The black background removed/made transparent would be awesome

as always, a sincere appreciation for all your effort.

**Comment by Tapiosinn** [comment]
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-states/us-local/cw/cw-wccb-us.png
@mophawka
