### ISSUE TITLE
tv4-tr logo Changed

### ISSUE THREAD

**Issue by UzunMuhalefet** [Tapiosinn/tv-logos#26]
**What logo would you like to see? Why?**
Tv4 (TR) changed its logo.

**What country is the channel shown?**
Turkey

**Links(optional)**
Best sources that I can find.
https://www.turkmedya.com.tr/tv4
https://www.turkmedya.com.tr/assets/img/logo/logo_tv4_yeni_2.png

**Comment by UzunMuhalefet** [comment]
TRT4K changed its logo too.
https://tr.wikipedia.org/wiki/TRT_4K#/media/Dosya:TRT_4K.svg

**Comment by Tapiosinn** [comment]
Logos added
@UzunMuhalefet
