### ISSUE TITLE
Turkish TV Channels

### ISSUE THREAD

**Issue by UzunMuhalefet** [Tapiosinn/tv-logos#27]
**What logo would you like to see? Why?**
4 Eylül TV
Aksu TV
Anadolu Dernek TV
Berat TV
Bizim Ev TV
Diyar TV
Dost TV
DRT Denizli
Edessa TV
Ekin Türk
Flash TV
FM TV
Gaziantep Olay TV
GS TV
Güneydoğu TV
HRT Akdeniz

**What country is the channel shown?**
Turkey

**Links(optional)**
Links are here for channels respectively. Sorry I could not find white versions for some channels.
https://canakanten.com/wp-content/uploads/4-eylul-tv.png
https://raw.githubusercontent.com/picons/picons/master/build-source/logos/aksutv.default.png
https://raw.githubusercontent.com/picons/picons/master/build-source/logos/anadoludernek.default.png
https://berattv.com.tr/wp-content/uploads/2020/10/Berat-tv-logo-yeni.png
https://yt3.ggpht.com/ytc/AKedOLS2ArJlOZ3uKNlICgDAHmsjBJNU1MYulLiJGXon=s900-c-k-c0x00ffffff-no-rj
https://www.diyartv.com.tr/images/logo.png
https://raw.githubusercontent.com/picons/picons/master/build-source/logos/dost.default.png
https://raw.githubusercontent.com/picons/picons/master/build-source/logos/drtdenizli.default.png
https://raw.githubusercontent.com/picons/picons/master/build-source/logos/edessatv.default.png
https://raw.githubusercontent.com/picons/picons/master/build-source/logos/ekinturk.default.png
https://raw.githubusercontent.com/picons/picons/master/build-source/logos/flashhd.default.png
https://raw.githubusercontent.com/picons/picons/master/build-source/logos/fmtelevizyonu.default.png
https://yt3.ggpht.com/2VYVUd6msmX6Ejx0CHfWpHhalHaKEVCQW0-f_jOxhTf32TbfxLrTPXR7rILhH08ru5HGGl3thg=s900-c-k-c0x00ffffff-no-rj
https://raw.githubusercontent.com/picons/picons/master/build-source/logos/gstv.default.png
http://www.guneydogutv.com/resimler/footerlogo.png
https://yt3.ggpht.com/ytc/AKedOLRWuTObyeQosJ7TsJJfOHz1OjSQJ8okf3JWofCK_g=s900-c-k-c0x00ffffff-no-rj

**Additional context(optional)**
Sorry for too many requests but I love your work and I want to improve. If you want I can publish more channels with sources :)

**Comment by Tapiosinn** [comment]
Logos added
Feel free to let me know of other logos, and I'll have a look when I have time.
@UzunMuhalefet
