### ISSUE TITLE
Turkish Channels

### ISSUE THREAD

**Issue by UzunMuhalefet** [Tapiosinn/tv-logos#28]
New list :) Thank you mate.
**What logo would you like to see? Why?**
Kanal 15
Kanal 23
Kanal 3
Kanal 33
Kanal 58
Kanal Ege
Kanal Urfa
Kent Türk
Manisa TV
Mercan TV
Pamukkale TV
Rehber TV
Tarım TV
Tatlıses TV
Tempo TV
tivi6
Toprak TV
tv1
tv264
TV Kayseri
Türk Haber

**What country is the channel shown?**
Turkey

**Links(optional)**
https://www.kanal15.com.tr/wp-content/uploads/2020/10/Kanal15Logopng-3.png
https://raw.githubusercontent.com/picons/picons/master/build-source/logos/kanal23.default.png
https://raw.githubusercontent.com/picons/picons/master/build-source/logos/kanal3-hilerethip.default.png
https://raw.githubusercontent.com/picons/picons/master/build-source/logos/kanal33.default.png
https://www.buyuksivas.com/wp-content/uploads/2017/09/kanal-58.png
https://static.daktilo.com/sites/423/uploads/2021/08/23/large/kanal-ege-logo-1629726420.png
https://raw.githubusercontent.com/picons/picons/master/build-source/logos/kanalurfa.default.png
https://www.facebook.com/kentturktv/photos/a.916817538412329/2128013830626021
https://www.facebook.com/tvmanisa/photos/a.132363181906496/132363001906514
https://raw.githubusercontent.com/picons/picons/master/build-source/logos/mercan.default.png
https://raw.githubusercontent.com/picons/picons/master/build-source/logos/pamukkale.default.png
https://www.facebook.com/RehberTV/photos/a.138698522906691/3786229314820242
https://www.tarimtv.gov.tr/uploads/logo/logo-tarim-31FnQ2ZNL1.png
https://raw.githubusercontent.com/picons/picons/master/build-source/logos/tatlises.default.png
https://raw.githubusercontent.com/picons/picons/master/build-source/logos/tempotv.default.png
https://tivi6.com.tr/wp-content/uploads/2021/07/ico.png
https://www.toprak.tv/wp-content/uploads/2020/05/cropped-TOPRAKTV-LOGO-1-son.png
http://www.tvbir.com.tr/images/logos/logo-1.png
https://api.tv264.gunesozturk.com/Uploads/img/logo/ubp82n3ksdk9n4xlof.jpg
https://raw.githubusercontent.com/picons/picons/master/build-source/logos/tv8int.default.png
https://tvkayseri.com.tr/wp-content/uploads/2020/10/logo1.jpg
https://raw.githubusercontent.com/picons/picons/master/build-source/logos/thturkhaber.default.svg)

**Additional context(optional)**
Add any other context or screenshots about the logo request here.

**Comment by Tapiosinn** [comment]
Logos added. Kanal3 was already on the list.
@UzunMuhalefet
