### ISSUE TITLE
Logos with Spelling Errors

### ISSUE THREAD

**Issue by Skates1616** [Tapiosinn/tv-logos#30]
bally-sports-winsconsin-us.png is incorrectly named.

It should be:

bally-sports-wisconsin-us.png

The plus version of the logo is correct.

Also, opra-winfrey-network-us.png is also misspelled.  It should be:

oprah-winfrey-network-us.png

**Comment by Tapiosinn** [comment]
Thank you, I have now fixed the errors.
@Skates1616
