### ISSUE TITLE
CBS 2 Chicago (WBBM)

### ISSUE THREAD

**Issue by Skates1616** [Tapiosinn/tv-logos#31]
**What logo would you like to see? Why?**
A logo for CBS 2 Chicago, it is currently missing from the repository.

**What country is the channel shown?**
Chicago, IL United States

**Links(optional)**
https://chicago.cbslocal.com/

**Additional context(optional)**
Add any other context or screenshots about the logo request here.

**Comment by Tapiosinn** [comment]
Logo added
https://github.com/Tapiosinn/tv-logos/blob/master/countries/united-states/us-local/cbs-2-wbbm-us.png
@Skates1616
