### ISSUE TITLE
Livenow from Fox

### ISSUE THREAD

**Issue by Skates1616** [Tapiosinn/tv-logos#33]
**What logo would you like to see? Why?**
A logo for streaming network LiveNOW from Fox.

**What country is the channel shown?**
Streaming.

**Links(optional)**
https://www.livenowfox.com/

**Additional context(optional)**

**Comment by Tapiosinn** [comment]
Added
https://github.com/Tapiosinn/tv-logos/blob/master/countries/united-states/live-now-fox-us.png
@Skates1616
