### ISSUE TITLE
Add Missing CW Logos

### ISSUE THREAD

**Issue by Skates1616** [Tapiosinn/tv-logos#34]
**What logo would you like to see? Why?**
Add missing CW logos for Atlanta, Pittsburgh, and Seattle.  The logos are currently not in the repo.

**What country is the channel shown?**
USA

**Links(optional)**
Atlanta (WUPA): https://cwatlanta.cbslocal.com/
Pittsburgh (WPCW): https://cwpittsburgh.cbslocal.com/
Seattle (KSTW): https://cwseattle.cbslocal.com/

**Additional context(optional)**

Thank you for your hardwork and dedication!

**Comment by Tapiosinn** [comment]
added
https://github.com/Tapiosinn/tv-logos/blob/master/countries/united-states/us-local/cw/cw-69-wupa-us.png
https://github.com/Tapiosinn/tv-logos/blob/master/countries/united-states/us-local/cw/cw-wpcw-us.png
https://github.com/Tapiosinn/tv-logos/blob/master/countries/united-states/us-local/cw/cw-11-kstw-us.png
@Skates1616
