### ISSUE TITLE
WFMZTV Logo

### ISSUE THREAD

**Issue by Skates1616** [Tapiosinn/tv-logos#35]
**What logo would you like to see? Why?**
Add a logo for WFMZTV.  It currently does not exist.

**What country is the channel shown?**
USA, Local (Philadelphia)

**Links(optional)**
https://www.wfmz.com/

**Additional context(optional)**
Add any other context or screenshots about the logo request here.

**Comment by Tapiosinn** [comment]
Added
https://github.com/Tapiosinn/tv-logos/blob/master/countries/united-states/us-local/69-wfmz-tv-us.png
@Skates1616
