### ISSUE TITLE
LocalNow

### ISSUE THREAD

**Issue by Skates1616** [Tapiosinn/tv-logos#36]
**What logo would you like to see? Why?**
Add a logo for LocalNow, it is currently missing.

**What country is the channel shown?**
USA, streaming station.

**Links(optional)**
https://localnow.com/

**Additional context(optional)**
Thank you again!

**Comment by Tapiosinn** [comment]
added
https://github.com/Tapiosinn/tv-logos/blob/master/countries/united-states/local-now-us.png
@Skates1616
