### ISSUE TITLE
ATN Cricket Plus/+

### ISSUE THREAD

**Issue by mophawka** [Tapiosinn/tv-logos#38]
**What logo would you like to see?**
ATN Cricket Plus/+

**In what country is the channel shown?**
Country: Canada

**Links to some version of the logo or the website for the channel(optional)**
Link: http://asiantelevision.net/channel/atn-cricket-plus  

http://www.asiantelevision.com/uploads/channel_logo/1507821977_atn-cricket-plus-web.png

https://upload.wikimedia.org/wikipedia/en/thumb/6/67/Cricket-Plus-tr.gif/300px-Cricket-Plus-tr.gif

**Additional information(optional)**
Info: please no black letters like in the original.

appreciate all your hard works as always. Thanks

**Comment by Tapiosinn** [comment]
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/canada/atn-cricket-plus-ca.png
@mophawka
