### ISSUE TITLE
Charlottle NC WCNC Local Channel

### ISSUE THREAD

**Issue by mophawka** [Tapiosinn/tv-logos#39]
**What logo would you like to see?**
Channel name: WCNC

**In what country is the channel shown?**
Country: US Local

**Links to some version of the logo or the website for the channel(optional)**
Link: https://www.wcnc.com/
https://www.wcnc.com/assets/shared-images/logos/wcnc.png

**Additional information(optional)**
Info: Thank you

**Comment by Tapiosinn** [comment]
https://raw.githubusercontent.com/Tapiosinn/tv-logos/master/countries/united-states/us-local/nbc-wcnc-us.png
@mophawka
