### ISSUE TITLE
UK - News (NBC News Now)

### ISSUE THREAD

**Issue by VoidMediaBoss** [Tapiosinn/tv-logos#42]
**What logo would you like to see?**
Channel name: NBC News Now)

**In what country is the channel shown?**
Country: UK

**Links to some version of the logo or the website for the channel(optional)**
Link: https://www.sky.com/tv-guide/20220408/4101-1/525

**Additional information(optional)**
Info:

**Comment by Tapiosinn** [comment]
Added
https://github.com/Tapiosinn/tv-logos/blob/master/countries/united-kingdom/nbc-news-now-uk.png
@VoidMediaBoss
