### ISSUE TITLE
Rakuten TV

### ISSUE THREAD

**Issue by 7Wuf8xG46TjwTtqYsNMJ** [Tapiosinn/tv-logos#45]
**What logo would you like to see?**
Channel names:
Rakuten TV - Action
Rakuten TV - British
Rakuten TV - Comedy
Rakuten TV - Drama
Rakuten TV - Family
Rakuten TV - Romance
Rakuten TV - Thrillers
Rakuten TV - Top Movies

**In what country is the channel shown?**
Country: Various

**Links to some version of the logo or the website for the channel(optional)**
Links:
Rakuten TV - Action:
https://provider-static.plex.tv/epg/cms/production/0bb201ee-218d-4b73-bb41-6551fdcc23d7/DE_ACTION_Logo_3-1920x1080.jpg
https://provider-static.plex.tv/epg/cms/production/b9efa1d6-c5c5-410d-b2f9-f251c03a112d/DE_ACTION_Logo_Final-2000x3000-OK.jpg
https://provider-static.plex.tv/epg/cms/production/7d9c8215-0c05-4506-a35c-80831ec4151d/DE_ACTION_Logo_2-1500x1000redux.png

Rakuten TV - British:
https://provider-static.plex.tv/epg/cms/production/eb8bd1b3-5f91-4a37-898e-1fe615e54d12/UK_Local_Logo_3-1920x1080.jpg
https://provider-static.plex.tv/epg/cms/production/9b6eb811-c6e5-42bb-ae97-db71502256e1/UK_LOCAL_Logo_1-2000x3000.jpg
https://provider-static.plex.tv/epg/cms/production/1f3234d9-d28e-4af0-9a7d-37521bc128ef/UK_local_Logo_2-1500x1000rdx.png

Rakuten TV - Comedy:
https://provider-static.plex.tv/epg/cms/production/556679ee-153a-4fac-a039-a410f937523c/UK_COMEDY_Logo_3-1920x1080.jpg
https://provider-static.plex.tv/epg/cms/production/b4d0d149-9dc5-4b2a-851f-6e51009ffa50/UK_COMEDY_Logo_1-2000x3000.jpg
https://provider-static.plex.tv/epg/cms/production/45449576-051c-4e6e-915c-d684e3683578/UK_COMEDY_Logo_2-1500x1000redux.png

Rakuten TV - Drama:
https://provider-static.plex.tv/epg/cms/production/b6478d0e-9754-4196-851f-ca027697b106/UK_DRAMA_Logo_3-1920x1080.jpg
https://provider-static.plex.tv/epg/cms/production/aae08626-5ff4-48f7-97a1-27552db657a4/UK_DRAMA_Logo_1-2000x3000.jpg
https://provider-static.plex.tv/epg/cms/production/f87b6fd5-dc0c-41d9-8ab0-ae5e9dc31482/UK_DRAMA_Logo_2-1500x1000rdx.png

Rakuten TV - Family:
https://provider-static.plex.tv/epg/cms/production/5a0a06ba-eb5b-4800-82f6-4b5e53b5b7a6/UK_Family-Logo_3-1920x1080.jpg
https://provider-static.plex.tv/epg/cms/production/5ec033ce-f844-4ef5-a4f8-20c8041970be/UK_FAM_Logo_Final-2000x3000.jpg
https://provider-static.plex.tv/epg/cms/production/48508ab1-b148-4c44-b407-0d015f6fdfae/UK_FAMILY_Logo_2-1500x1000rdx.png

Rakuten TV - Romance:
https://provider-static.plex.tv/epg/cms/production/eb9ea8a0-679c-4158-899c-6b0793bf3e9f/UK_Romantic-Logo_3-1920x1080.jpg
https://provider-static.plex.tv/epg/cms/production/5997ca3d-40e1-471d-9d72-a81dfa37c47c/UK_ROMANCE_Logo_1-2000x3000.jpg
https://provider-static.plex.tv/epg/cms/production/7aa3560b-4070-4e12-99a4-2dc684288c94/UK_Romance_Logo_2-1500x1000rdx.png

Rakuten TV - Thrillers:
https://provider-static.plex.tv/epg/cms/production/010f6c8c-e072-4c92-8b4f-8cd019ab9550/UK_thriller-Logo_3-1920x1080.jpg
https://provider-static.plex.tv/epg/cms/production/bd157fcb-063a-4c96-8985-b75daebc899d/UK_THRILLER_Logo_1-2000x3000.jpg
https://provider-static.plex.tv/epg/cms/production/52a1139e-6190-432b-80d2-3f1517f53968/UK_THRILLER_Logo_2-1500x1000rdx.png

Rakuten TV - Top Movies:
https://provider-static.plex.tv/epg/cms/production/5c9259f5-13c5-4c42-8ebb-b205824b1dcc/UK_TOP-MOVIES_Logo_3-1920x1080.jpg
https://provider-static.plex.tv/epg/cms/production/26c0d8a4-8264-4ef9-b318-cb09f807efaf/UK_TOP_MOVIES_Logo_1-2000x3000.jpg
https://provider-static.plex.tv/epg/cms/production/df01971c-fbd2-4440-9cd7-b05a3cfaa5e5/UK_TOP-MOVIES_Logo_2-1500x1000redux.png

**Additional information(optional)**
Info: I've included multiple images for each in the help to find an easier one for you to edit.

**Comment by Tapiosinn** [comment]
Logos added to VOD folder https://github.com/Tapiosinn/tv-logos/tree/master/misc/vod
@7Wuf8xG46TjwTtqYsNMJ
