### ISSUE TITLE
RealityXtra, HorrorXtra, Legend

### ISSUE THREAD

**Issue by VoidMediaBoss** [Tapiosinn/tv-logos#47]
**What logo would you like to see?**
Channel name: RealityXtra, HorrorXtra, Legend

**In what country is the channel shown?**
Country: UK 

**Links to some version of the logo or the website for the channel(optional)**
Link: sky official website

**Additional information(optional)**
Info: N/A
![Screenshot 2022-06-30 at 11 23 13](https://user-images.githubusercontent.com/90480108/176654767-a2ecb58c-c5a7-4058-ba6b-12ea62f14f05.png)
![Screenshot 2022-06-30 at 11 23 00](https://user-images.githubusercontent.com/90480108/176654771-51cc1393-1ad1-43cc-8d0e-7f261f72dde9.png)

**Comment by Tapiosinn** [comment]
Logos added
@VoidMediaBoss
