### ISSUE TITLE
Claro Sports

### ISSUE THREAD

**Issue by mophawka** [Tapiosinn/tv-logos#48]
**What logo would you like to see?**
Channel name: Claro Sports

**In what country is the channel shown?**
Country: South America (Multiple Countries)

**Links to some version of the logo or the website for the channel(optional)**
Link: http://www.clarosports.com.tmx-internacional.net/futbol

**Additional information(optional)**
Info: http://www.clarosports.com.tmx-internacional.net/recursos_estaticos/img/logo-clarosports.png

while the OG logo is hz would love to see a square logo as well (example attached). Thank you as always
![cXSpOTJyh1zyS_df9d5aa9FbmdE2G2r_TbE0jBVXHB6R7gJ0BBq1OI-1UhVnQfYeVfH0DscDH57fc7WfEWVYsg](https://user-images.githubusercontent.com/45985083/181606171-480dbd67-a9dc-46a2-958c-2cb8fbef546c.png)

**Comment by Tapiosinn** [comment]
Logos added to Latin America
@mophawka
