### ISSUE TITLE
Sky Sports Main Event Ultra HDR

### ISSUE THREAD

**Issue by VoidMediaBoss** [Tapiosinn/tv-logos#49]
**What logo would you like to see?**
Channel name: Sky Sports Main Event Ultra HDR

**In what country is the channel shown?**
Country: UK

**Links to some version of the logo or the website for the channel(optional)**
Link: 

**Additional information(optional)**
Info:
![IMG_1176](https://user-images.githubusercontent.com/90480108/181908744-44aa3441-d7fc-42f3-b8a4-0b73a34e0771.jpeg)

**Comment by Tapiosinn** [comment]
https://github.com/Tapiosinn/tv-logos/blob/master/countries/united-kingdom/screen-bug/sky-sports-main-event-ultra-hdr-bug-uk.png
@VoidMediaBoss
