### ISSUE TITLE
Bt Sport 4-10

### ISSUE THREAD

**Issue by VoidMediaBoss** [Tapiosinn/tv-logos#50]
**What logo would you like to see?**
Channel name: BT Sport 4-10

**In what country is the channel shown?**
Country: UK 
<img width="1136" alt="Screenshot 2022-08-01 at 09 46 37" src="https://user-images.githubusercontent.com/90480108/182110337-5de09fec-046c-4f83-9241-141e970c448a.png">

**Links to some version of the logo or the website for the channel(optional)**
Link: https://www.bt.com/sport/watch/live-now

**Additional information(optional)**
Info:

**Comment by VoidMediaBoss** [comment]
Hey hope you are well, any update on this? Cheers!!

**Comment by VoidMediaBoss** [comment]
if you could get the HD options as well that would be awesome

**Comment by Tapiosinn** [comment]
Logos added to UK folder
@VoidMediaBoss
