### ISSUE TITLE
VIRGIN MEDIA FOUR

### ISSUE THREAD

**Issue by VoidMediaBoss** [Tapiosinn/tv-logos#52]
**What logo would you like to see?**
Channel name: VIRGIN MEDIA FOUR

**In what country is the channel shown?**
Country: UK - IRELAND

**Links to some version of the logo or the website for the channel(optional)**
Link: sky.com (ireland)

**Additional information(optional)**
Info: n/a

**Comment by Tapiosinn** [comment]
Logo added
@VoidMediaBoss
