### ISSUE TITLE
Sporty Stuff TV

### ISSUE THREAD

**Issue by 0845** [Tapiosinn/tv-logos#6]
**What logo would you like to see? Why?**
Sporty Stuff TV

**What country is the channel shown?**
United Kingdom. 

**Links(optional)**
https://rxtvinfo.com/2021/greyhound-racing-moves-to-new-hd-sports-channel

**Additional context(optional)**
New channel: 437 on Sky Sporty Stuff HD

**Comment by Tapiosinn** [comment]
https://github.com/Tapiosinn/tv-logos/blob/master/countries/united-kingdom/sporty-stuff-tv-uk.png
@0845
