### ISSUE TITLE
Ignition TV - .za

### ISSUE THREAD

**Issue by mophawka** [Tapiosinn/tv-logos#7]
**What logo would you like to see? Why?**
Ignition TV

**What country is the channel shown?**
South Africa

**Links(optional)**
https://www.timeslive.co.za/motoring/
https://static.wikia.nocookie.net/logopedia/images/f/fc/Ignition.jpg
https://lh3.googleusercontent.com/AAaJuKC37FaK73GxeE29y6xIo0pFiL4VB5e62miI-1JVpeC1-CqOmzqBJm2eMptLfR1KGGdFsbt-_FAAAisp=s1200

**Additional context(optional)**
Thank you for your consideration!

**Comment by Tapiosinn** [comment]
Added, I can't do the flare effect, takes too long.
https://github.com/Tapiosinn/tv-logos/blob/master/countries/south-africa/ignition-za.png
