### ISSUE TITLE
Next Level Sports, formerly known as Eleven Sports Network

### ISSUE THREAD

**Issue by mophawka** [Tapiosinn/tv-logos#8]
**What logo would you like to see? Why?**
Next Level Sports, previously Eleven Sports Network

**What country is the channel shown?**
US

**Links(optional)**
https://simulationfl.net/wp-content/uploads/2021/03/black-logo-on-white-bg_Sports-1-2048x512.png
https://simulationfl.net/wp-content/uploads/2021/03/SFL-plus-Next-Level-Sports.fw_.png
https://i.ibb.co/3sH48w5/Untitled.png (channel advertised logo)

**Additional context(optional)**
the second link with the yellow top and bottom bars as well as arrow is official channel logo (as shown in link 3) and preferred but that's entirely up to your capable hands. 
Thanks for the consideration

**Comment by Tapiosinn** [comment]
@mophawka 

I've added the logo:
https://github.com/Tapiosinn/tv-logos/blob/5758ca33da0b7cf663ec6089dc440f247d04dde7/countries/united-states/next-level-sports-us.png
