### ISSUE TITLE
TX / Houston / My 20 Vision KTXH Local network

### ISSUE THREAD

**Issue by mophawka** [Tapiosinn/tv-logos#9]
**What logo would you like to see? Why?**
KTXH Houston re-branded as "My 20 Vision"

**What country is the channel shown?**
United States - Houston Texas Local

**Links(optional)**
https://i.imgur.com/pawiunZ.png (hz)
https://i.imgur.com/QNJz20S.jpg
https://i.imgur.com/6guvYjh.png ( Logo shown on some programing)

https://www.facebook.com/My20Houston/

**Additional context(optional)**
Thank you for your consideration

**Comment by Tapiosinn** [comment]
Added
https://github.com/Tapiosinn/tv-logos/blob/master/countries/united-states/us-local/mytv/my-20-vision-ktxh-us.png
https://github.com/Tapiosinn/tv-logos/blob/master/countries/united-states/us-local/mytv/my-20-vision-ktxh-hz-us.png
@mophawka
